services:
  - type: web
    name: stock-analyzer-pro-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python consolidated_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ZERODHA_API_KEY
        sync: false
      - key: ZERODHA_API_SECRET
        sync: false
      - key: ZERODHA_ACCESS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REQUIRE_AUTH
        value: false
      - key: CORS_ORIGINS
        value: https://stock-analyzer-pro.vercel.app,https://stock-analyzer-pro-git-prototype-aaryan-manawats-projects.vercel.app,https://stock-analyzer-cl9o3tivx-aaryan-manawats-projects.vercel.app,https://stockanalyzer-pro.vercel.app

