# LLM Agent Assignments Configuration
# Maps each agent to specific provider and model for optimal performance

# Default configuration - all agents use Gemini Flash initially
# This will be optimized based on performance testing in later phases
default:
  provider: "gemini"
  model: "gemini-2.5-flash"
  enable_code_execution: true
  max_retries: 3
  timeout: 60
  # API Key Management Configuration
  # Options:
  #   - "round_robin": Rotate through all available keys globally (good for load distribution)
  #   - "agent_specific": Each agent gets a specific key index (good for tracking)
  #   - "single": Use one key for all requests (fallback mode)
  api_key_strategy: "round_robin"
  api_key_index: null  # null for round_robin/single, specific index (0-4) for agent_specific

# Agent-specific overrides
# Agents can use different providers/models based on their specific needs
agents:
  
  # Indicator Analysis Agent
  indicator_agent:
    provider: "gemini" 
    model: "gemini-2.5-pro"  # Fast for frequent indicator analysis
    enable_code_execution: true  # Needs code execution for calculations
    max_retries: 3
    timeout: 90
    
  # Sector Analysis Agent
  sector_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Good balance for sector synthesis
    enable_code_execution: false  # Mostly text synthesis
    max_retries: 3
    timeout: 90
    
  # Risk Analysis Agent
  risk_agent:
    provider: "gemini" 
    model: "gemini-2.5-flash"  # Fast for risk calculations
    enable_code_execution: true  # Needs calculations
    max_retries: 3
    timeout: 90
    
  # Final Decision Agent
  final_decision_agent:
    provider: "gemini"
    model: "gemini-2.5-pro"  # Best quality for final decisions
    enable_code_execution: true  # Needs synthesis calculations
    max_retries: 3
    timeout: 90
    api_key_strategy: "round_robin"  # Use rotating keys for critical agent
    
  # Multi-Timeframe Analysis Agent
  mtf_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Fast for multi-timeframe analysis
    enable_code_execution: true  # May need calculations for cross-timeframe validation
    max_retries: 3
    timeout: 100  # MTF analysis can be comprehensive
    
  # Institutional Activity Agent (Volume)
  institutional_activity_agent:
    provider: "gemini"
    model: "gemini-2.5-pro"  # Fast for institutional volume analysis
    enable_code_execution: true  # Needs code execution for volume calculations
    max_retries: 3
    timeout: 90  # Institutional analysis standardized to 90s
    api_key_strategy: "agent_specific"  # Dedicated key for consistent tracking
    api_key_index: 0  # Always use GEMINI_API_KEY1
    
  # Volume Confirmation Agent
  volume_confirmation_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Fast for price-volume confirmation analysis
    enable_code_execution: true  # Needs code execution for volume calculations
    max_retries: 3
    timeout: 90  # Volume confirmation analysis
    api_key_strategy: "agent_specific"  # Dedicated key for consistent tracking
    api_key_index: 1  # Always use GEMINI_API_KEY2
    
  # Volume Momentum Agent
  volume_momentum_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Fast for volume momentum analysis
    enable_code_execution: true  # Needs code execution for momentum calculations
    max_retries: 3
    timeout: 150  # Volume momentum analysis
    api_key_strategy: "agent_specific"  # Dedicated key for consistent tracking
    api_key_index: 2  # Always use GEMINI_API_KEY3
    
  # Volume Anomaly Agent
  volume_anomaly_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Fast for volume anomaly detection
    enable_code_execution: true  # Needs code execution for anomaly calculations
    max_retries: 3
    timeout: 90  # Volume anomaly analysis
    
  # Support Resistance Agent (Volume)
  support_resistance_agent:
    provider: "gemini"
    model: "gemini-2.5-flash"  # Fast for volume-based support/resistance analysis
    enable_code_execution: true  # Needs code execution for level calculations
    max_retries: 3
    timeout: 90 # Support/resistance analysis

# Future provider configurations (will be activated in Phase 7)
future_configs:
  
  # OpenAI configurations (commented out for now)
  # risk_agent_openai:
  #   provider: "openai"
  #   model: "gpt-4o"
  #   max_tokens: 4000
  #   temperature: 0.1
  #   max_retries: 3
  #   timeout: 60
  
  # Claude configurations (commented out for now)  
  # final_decision_claude:
  #   provider: "claude"
  #   model: "claude-3-5-sonnet"
  #   max_tokens: 4000
  #   temperature: 0.1
  #   max_retries: 3
  #   timeout: 60

# Environment-specific overrides
environments:
  
  development:
    # Use faster/cheaper models for development
    default:
      model: "gemini-2.5-flash"
      timeout: 30
    # Don't override timeouts for agents that specifically need longer times
    agents:
      indicator_agent:
        timeout: 90  # Respect agent-specific timeout
      final_decision_agent:
        timeout: 90  # Respect agent-specific timeout
      
  staging:
    # Same as production but with shorter timeouts for non-critical agents
    default:
      timeout: 45
    # Don't override timeouts for agents that specifically need longer times
    agents:
      indicator_agent:
        timeout: 90  # Respect agent-specific timeout
      final_decision_agent:
        timeout: 90  # Respect agent-specific timeout
      
  production:
    # Production-optimized settings
    default:
      max_retries: 5  # More retries in production
      timeout: 90  # Longer timeouts for reliability
